[project]
name = "dry-box"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "esphome>=2025.6.1",
    "fastapi[standard]>=0.115.12",
    "grip>=4.6.2",
]
